---
title: ''
output:
  html_document:
    theme: NULL
    css: tk_page_style.css
---

Management
===============================
####In 2016 and 2017, TomKat Ranch staff recorded the movement of animals in and out of fields to track grazing intensity in each field. Point Blue Conservation Science summarized these data as the total number of days grazed and the number of animal-days per acre (ADA) by season.{#intro}

### Guiding Principle

Manipulate timing, intensity and duration of grazing events in a way that supports livestock health while also improving ecological functioning on the landscape (as measured by our goals).


### Animal Days per Acre (ADA)

<i>Choose a season at bottom left. Click on any of the fields to learn more.</i>

<center>
<iframe src="mgmt_map1.html" style="border: none;" width = 100%; height = 550px;></iframe>
</center>


### Total grazing days

<center>
<iframe src="mgmt_map2.html" style="border: none;" width = 100%; height = 550px;></iframe>
</center>


--------------------------------------------
### Glossary

<b>Animal days per acre:</b> Calculated as the sum total of the number of animals present per day divided by the number of acres.

<b>Total grazing days:</b> Calculated as the total number of days animals were present in the field.


### About this page
This interactive web page was produced in [R](https://www.R-project.org/){target="_blank"} using [rmarkdown](https://rmarkdown.rstudio.com/){target="_blank"} and the packages [leaflet](http://rstudio.github.io/leaflet/){target="_blank"} and [plotly](https://plot.ly/r/){target="_blank"}. The code used to produce this web page is available on [Github](https://github.com/pointblue/tomkat){target="_blank"}.

### For more information

Please contact:  
[Nat Seavy, Ph.D.](mailto:nseavy@pointblue.org)  
Research Director  
Pacific Coast and Central Valley Group  
[Point Blue Conservation Science](https://www.pointblue.org){target="_blank"}
