---
title: ''
output:
  md_document:
    variant: markdown_github
---

TomKat State of the Ranch Data Pages
=========================
[Point Blue Conservation Science](http://www.pointblue.org) has partnered with [TomKat Ranch](https://tomkatranch.org) to collect many different types of data reflecting changing conditions on the ranch. Every year, we summarize these data and provide Ranch staff with an update. The update including data through fall 2018 is currently underway. This project contains the data and code for producing these data summaries as individual web pages.

### CURRENT STATUS:
All pages are currently viewable at: [https://pointblue.github.io/TomKat](https://pointblue.github.io/TomKat/)

### CHANGES IN 2018:

#### Overall
* Major structural overhaul to work with new TomKat website, with each display piece produced independently  
* Hosted on Github
* Style/formatting matched to new TomKat Ranch website
* Added text describing SMART goals on each page
* __Future wishlist:__ Add more context linking SMART goals to observations to date

#### Weather
* All local weather station data included through December 17, 2018
* Regional drought index data included through November 2018
* Switch from dygraphs to plotly graphics

#### Soil
* 2018 soil sampling data replaces 2015 data as current soil metrics map
* Soil metrics legend changed to show actual values rather than just high/low
* Added change map showing differences between 2015 and 2018
* Added map showing soil microbial data
* Marked soil sampling points where compost was added
* Made terrain easier to see
* __TO DO:__ Add map showing soil fungal data
* __Future wishlist:__ Add soil nutrients change map

#### Vegetation
* 2018 vegetation survey data replaces previous data as current veg map
* Vegetation change map recalculated as a change in mean values between two sets of years (2012-14 and 2016-18) and legend updated to highlight large changes relative to 2012-14 values
* Vegetation trends updated through 2018 and switched from dygraphs to plotly graphics
* Added map of herbaceous vegetation diversity
* __Future wishlist:__ Add links to pasture plants guide and species lists

#### Water
* All stream gauge data included through August 16, 2018
* Switch from dygraphs to plotly graphics
* __Future wishlist:__ Add info about steelhead, water quality data

#### Birds
* Focal species abundance map recalculated to include all point count data through 2018
* Species richness estimates map recalculated to include all point count data through 2018
* Annual focal species abundance trend and grassland vs riparian species richness trends recalculated to include all point count data through 2018
* Switched trend graphs from dygraphs to plotly graphics
* __Future wishlist:__ Add links to wildlife/bird checklists; add photos; add info about banding and Christmas Bird Count surveys; Compare bird densities to management data (difficult with annual sampling effort)

#### Management
* 2017-18 data replaces older management data, now in pastures aligned with vegetation survey data
* Summary statistics (ADA and total grazing days) recalculated with new data
* __Future wishlist:__ Add map of ranch trials, mowing history, grazing chart


