---
title: ''
output:
  html_document:
    theme: spacelab
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pointblue.palette <-
  c('#4495d1',
    '#74b743',
    '#f7941d',
    '#005baa',
    '#bfd730',
    '#a7a9ac',
    '#666666')
```

<a id="top"></a>

TomKat Ranch: Vegetation
===============================
Point Blue Conservation Science has surveyed grassland vegetation across TomKat Ranch each summer since 2011. We examined patterns in the [current vegetation cover](#cover) and [diversity](#diversity) in each pasture, [changes over time](#diff) in each pasture, and [ranch-wide vegetation trends](#trends).

<a id='cover'></a>

### Current vegetation cover

Vegetation cover varies across the ranch, likely reflecting the interaction between local soil conditions, management decisions, and weather. In 2018, <b>native grasses</b> were more common on the west side of the ranch, while <b>invasive weeds</b> were more prevalent on the central and eastern parts of the ranch.


<i>Choose a vegetation type at bottom left. Click on any of the pastures to learn more.</i>


<iframe src="vegetation_map1.html" style="border: none;" width = 80%; height = 550px;></iframe>


[Back to top](#top)


<a id='diff'></a>

### Vegetation changes over time  

Vegetation cover changes over time, and the amount of change has varied by pasture. Again, these changes likely reflect the influences of both weather (drought) and management decisions, and depend on local soil conditions. Comparing 2016-2018 to 2012-2014, perennial and native grass cover has more than doubled in several pastures.


<i>Choose a vegetation type at bottom left. Click on any of the pastures to learn more.</i>


<iframe src="vegetation_map2.html" style="border: none;" width = 80%; height = 550px;></iframe>


[Back to top](#top)


<a id='trends'></a>

### Ranch-wide vegetation trends
  
Since 2012, <font color='`r pointblue.palette[1]`'><b>grass cover</b></font> dropped slightly during the drought and rebounded in 2018. <font color='`r pointblue.palette[2]`'><b>Bare ground</b></font> has been declining since 2014, and in 2018, <font color='`r pointblue.palette[4]`'><b>invasive weeds</b></font> were at their lowest levels yet.


<iframe src="vegetation_graph1.html" style="border: none;" width = 80%; height = 500px;></iframe>


[Back to top](#top)


#### Grasses  

Among grasses, <font color='`r pointblue.palette[3]`'><b>perennial grasses</b></font> and <font color='`r pointblue.palette[2]`'><b>native grasses</b></font> are trending upward.


<iframe src="vegetation_graph2.html" style="border: none;" width = 80%; height = 500px;></iframe>


[Back to top](#top)


<a id='diversity'></a>

### Current vegetation diversity

The number of plant species in each pasture varies across the ranch. We summarized the average number of species detected in 2016-2018, excluding shrubs and trees.

<iframe src="vegetation_map3.html" style="border: none;" width = 80%; height = 550px;></iframe>


[Back to top](#top)



### Glossary

**Perennial grasses:** Grasses that can survive for many years, whereas annual grasses germinate from seed, reproduce, and die each year. Perennial grasses generally turn green sooner, stay green longer, produce more biomass, and are more drought-tolerant than annual grasses. Their deep roots stabilize soil, improve water infiltration, and recycle nutrients. 

**Native grasses:** California native grasses are perennials, which have been largely displaced by exotic annual grasses.

**Forbs:** Herbaceous flowering plants that are not grasses, sedges or rushes.

[Back to top](#top)


-------------
### About this page

This interactive web page was produced in [R](https://www.R-project.org/) using [rmarkdown](https://rmarkdown.rstudio.com/) and the packages [leaflet](http://rstudio.github.io/leaflet/) and [plotly](https://plot.ly/r/). The code used to produce this web page is available on [Github](https://github.com/pointblue/tomkat).


### For more information

Please contact:  
[Nat Seavy, Ph.D.](mailto:nseavy@pointblue.org)  
Research Director  
Pacific Coast and Central Valley Group  
Point Blue Conservation Science  


[Back to top](#top)
