---
title: ''
output:
  html_document:
    theme: spacelab
    css: tk_custom.css 
    smart: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pointblue.palette <-
  c('#4495d1',
    '#74b743',
    '#f7941d',
    '#005baa',
    '#bfd730',
    '#a7a9ac',
    '#666666')
```

<a id="top"></a>

TomKat Ranch: Vegetation
===============================
Point Blue Conservation Science has surveyed grassland vegetation across TomKat Ranch each summer since 2011. We examined patterns in the [current distribution of vegetation](#distribution) across the ranch, [pasture-specific changes](#diff) in vegetation since 2012, and [ranch-wide vegetation trends](#trends). [Explore data](#table).

<a id='distribution'></a>

### Current Vegetation Distribution 

In 2018, <b>perennial grasses</b> were more common on the west side of the ranch, while <b>invasive weeds</b> are more prevalent on the central and eastern parts of the ranch.


<i>Choose a vegetation type at bottom left. Click on any of the pastures to learn more.</i>


<iframe src="docs/vegetation_map1.html" style="border: none;" width = 80%; height = 500px;></iframe>


[Back to top](#top)


<a id='diff'></a>

### Pasture-specific changes  
Pasture-specific changes in vegetation cover may reflect the interaction between weather, local soil conditions, and pasture-specific management decisions. Since 2012, <b>perennial</b> and <b>native grasses</b> have increased more on the west side of the ranch.


<i>Choose a vegetation type at bottom left. Click on any of the pastures to learn more.</i>


<iframe src="docs/vegetation_map2.html" style="border: none;" width = 80%; height = 500px;></iframe>


[Back to top](#top)