---
title: 'Soil'
output:
  html_document:
    theme: NULL
    css: tk_page_style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## input files
masterdat <- 'data_master/TK_soil_master.csv'

library(tidyverse)
nsites <- read_csv(here::here(masterdat)) %>% 
  select(`Point Name`) %>%
  distinct() %>%
  count()
```

#### Since 2014, Point Blue Conservation Science has tested soils at `r nsites` sites across TomKat Ranch. These data allow us to evaluate soil productivity throughout the ranch and track changes over time. {#intro}


### SMART Goals

<b>Increase soil sponginess:</b> All RMN points surpass NRCS compaction and water infiltration targets by 2020.

<b>Increase soil organic carbon (SOC):</b> All RMN points gain 0.5% SOC in 0-10 cm by 2021.*

&ast;*Of the points that gained soil carbon on TomKat Ranch between 2015-2018, 0.5% was the average magnitude of change. We therefore feel this goal is ambitious but achievable.*


### Soil productivity

In 2018, we measured three indicators of soil productivity: organic carbon content at two depths (0-10cm and 10-40cm), surface soil bulk density, and water infiltration rates. We also produced an overall score combining all three indicators. 

In the map below, each point represents a soil sample location, with colors representing the score for each indicator. For carbon, the inner circle represents the surface soil sample (0-10 cm deep), and the outer circle represents the deeper soil sample (10-40 cm). Two locations where compost was applied are marked with a heavy black border.  

<i>Choose one metric at a time at bottom left. Click on any of the survey points for details.</i>

<center>
<iframe src="widget/soil_map1.html" style="border: none;" width = 100%; height = 550px;></iframe>
</center>



### Changes in soil productivity

We compared data collected in 2018 to data collected in 2014 to identify locations where each productivity indicator have improved or declined. Locations where compost was applied are marked with a heavy black border. Note that lower values in bulk density and water infiltration represent improvements.

<i>Choose one metric at a time at bottom left. Click on any of the survey points to learn more.</i>

<center>
<iframe src="widget/soil_map2.html" style="border: none;" width = 100%; height = 550px;></iframe>
</center>



### Soil nutrient concentrations
In 2015, we measured the pH and the concentrations soil nutrients important to plant growth at two soil depths. In the map below, the inner circle represents the surface soil sample (0-10 cm deep), and the outer circle represents the deeper soil sample (10-40 cm). 

<i>Choose one metric at a time at bottom left. Click on any of the survey points to learn more.</i>

<center>
<iframe src="widget/soil_map3.html" style="border: none;" width = 100%; height = 550px;></iframe>
</center>



### Soil microbes
In 2018, we analyzed the richness and composition of soil bacterial communities by sequencing DNA. Click on any of the survey points to see a comparison of the proportion of bacterial phyla present at the surface and in deeper soils.</i>
 
<center>
<iframe src="widget/soil_map4.html" style="border: none;" width = 100%; height = 550px;></iframe>
</center>

--------------------------------------
### Glossary

<b>Bulk density:</b> An indicator of soil compaction, bulk density is measured as the weight of a soil sample divided by its volume (grams/cm^3^). Compacted soils have a higher bulk density, with reduced pore space for water infiltration, water retention, root growth, soil aeration, and seedling germination.

<b>Water infiltration rate:</b> Also an indicator of soil compaction, water infiltration rate is measured as the time required for soil to absorb water (minutes per inch of water). Compacted soils take longer to absorb water, increasing runoff and decreasing water available for local plant growth.

<b>Organic carbon content:</b> An indicator of soil organic matter and soil productivity, organic carbon is measured as the percent of soil volume made up by organic carbon. Productive soils have an abundant microbial community that contribute to high levels of soil organic matter, driving plant growth and improving soil stabilization and capacity for storing water.

<b>Overall productivity score:</b> To identify the overall most productive locations within TomKat Ranch, or the least productive locations that may be good candidates for management actions, we combined values of all 3 soil indicators above into one overall score. We fit [empirical cumulative distribution functions](https://www.r-bloggers.com/exploratory-data-analysis-conceptual-foundations-of-empirical-cumulative-distribution-functions/){target="_blank"} to each productivity indicator (including separate scores for surface and deeper soil carbon) that effectively ranked each sampling location against each other. We reversed the bulk density and water infiltration rankings because for these indicators, lower values are better for soil productivity. We then calculated an overall percentile score as the mean of these individual percentile scores, weighting each indicator equally, so that a high value represents a relatively high overall productivity. <b>*Note:</b> These scores are only based on comparing these locations at TomKat to each other and not to values that may be found elsewhere on the ranch or beyond. 

<b>Bacterial and fungal richness:</b> The number of bacterial and fungal species observed in each soil sample. (Species were determined using operational taxonomic units (OTUs) at 97% sequence similarity. An OTU is composed of a group of closely related individuals.) 

<b>Bacterial phyla:</b> A level of taxonomic classification that falls between kingdom and class. While birds and plants are often discussed at the genus or species level, bacteria are often discussed at the phylum level. Some ecological traits and life strategies are shared at this broad level, so that meaningful interpretations can be inferred. For example, differences in traits associated with an <b>oligotrophic</b> lifestyle (microbes that prefer low nutrient and carbon conditions) or <b>copiotrophic</b> lifestyle (microbes that prefer high nutrient and carbon conditions) can occur at the phylum level. 

* Bacteroidetes, Actinobacteria, and Firmicutes are generally considered to be <b>copiotrophs</b>.  
* Acidobacteria and Verrucomicrobia are generally considered to be <b>oligotrophs</b>.


### About this page  
This interactive web page was produced in [R](https://www.R-project.org/){target="_blank"} using [rmarkdown](https://rmarkdown.rstudio.com/){target="_blank"} and the packages [leaflet](http://rstudio.github.io/leaflet/){target="_blank"} and [plotly](https://plot.ly/r/){target="_blank"}. The code used to produce this web page is available on [Github](https://github.com/pointblue/tomkat){target="_blank"}.


### For more information

Please contact:  
[Chelsea Carey, PhD](https://www.pointblue.org/employee_bios/chelsea-carey/){target="_blank"}  
Senior Soil Ecologist  
Working Lands Group  
[Point Blue Conservation Science](https://www.pointblue.org){target="_blank"}
