---
title: 'Birds'
output:
  html_document:
    theme: NULL
    css: tk_page_style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

source(here::here('src/process_bird_data.R'))
dat <- readr::read_csv(here::here('data_clean/TOKA_birds_main.csv'))
nspecies = count_species(dat)
nsurveys = count_surveys(dat)
```

#### Since 2010, Point Blue Conservation Science has conducted <b>`r format(nsurveys, big.mark=',')` bird surveys</b> across TomKat Ranch during May and June and detected a total of <b>`r nspecies` bird species</b>. Each year, biologists conduct point count surveys for birds at a random sample of points chosen from a grid across the ranch, as well as at 12 points in riparian vegetation along Honsinger Creek. We analyzed this data to examine spatial patterns and trends in species richness and in grassland bird abundance across the ranch.{#intro}


### SMART Goals
<b>Increase grassland breeding birds:</b> Increase densities to an average of 4.25 birds per 10 acres by 2020.

<b>Support riparian birds:</b> Continue increasing riparian bird populations at current rates (Wilson's Warbler, Swainson's Thrush, Song Sparrow). Maintain high bird species richness in Honsinger Creek (20-50 species per point).


### Average focal species abundance 

The density of grassland focal species (Grasshopper Sparrow and Savannah Sparrow) varies across the ranch. We compiled  bird survey data across 2010-`r max(dat$Year)` to estimate the overall average density (birds per 10 acres) of each species at each survey point across the ranch.


<i>Choose a focal species at bottom left. Click on any of the grid cells for the density estimate.</i>

<center>
<iframe src="../docs/widget/bird_map_density.html" style="border: none;" width = 100%; height = 550px;></iframe>
</center>



### Focal species declines 
  
Since 2010, we have observed a slight ranch-wide decline in the density of Savannah Sparrows and Grasshopper Sparrows.

<center>
<iframe src="../docs/widget/bird_trend_density.html" style="border: none;" width = 100%; height = 450px;></iframe>
</center>



### Species richness concentrated along Honsinger Creek  
  
The shading in this map shows the estimated number of species ever detected near a bird survey station, with darker colors representing more species. Honsinger Creek is a hotspot of bird species richness, with some of the highest numbers of species, but there are also some other hotspots across the ranch.

<i>Click on any of the points or grid cells for the number of species detected.</i>

<center>
<iframe src="../docs/widget/bird_map_richness.html" style="border: none;" width = 100%; height = 550px;></iframe>
</center>



### Decline in grassland species richness  
Ranch-wide, there were initially more total species in grassland point than in riparian points, but grassland species richness has declined in recent years while riparian richness has remained steady through the drought.

<center>
<iframe src="../docs/widget/bird_trend_richness.html" style="border: none;" width = 100%; height = 450px;></iframe>
</center>

-------------

### About this page

This interactive web page was produced in [R](https://www.R-project.org/){target="_blank"} using [rmarkdown](https://rmarkdown.rstudio.com/){target="_blank"} and the packages [leaflet](http://rstudio.github.io/leaflet/){target="_blank"} and [plotly](https://plot.ly/r/){target="_blank"}. The code used to produce this web page is available on [Github](https://github.com/pointblue/tomkat){target="_blank"}.


### For more information

Please contact:  
[Chelsea Carey, PhD](https://www.pointblue.org/employee_bios/chelsea-carey/){target="_blank"}  
Senior Soil Ecologist  
Working Lands Group  
[Point Blue Conservation Science](https://www.pointblue.org){target="_blank"}
